# CANAL DE ATENCION DE OSIPTEL

INSERT INTO `canal_atencions` (`nombre`) VALUES
('Email'),
('Personal'),
('Telefono'),
('Visita Empresa'),
('Web'),
('Carta'),
('Facebook'),
('Twitter');

## EMPRESA OPERADORA O ENTIDAD DE REFERENCIA

INSERT INTO `enres` (`nombre`) VALUES
('AMERICA MOVIL PERU S.A.C.'),
('DIRECTV PERU S.R.L'),
('ENTEL PERÚ S.A. (antes NEXTEL DEL PERÚ S.A.)'),
('OSIPTEL'),
('TELEFÓNICA DEL PERÚ S.A.A.'),
('AMERICATEL PERÚ S.A.'),
('INDECOPI'),
('VIETTEL PERU S.A.C.'),
('Telefónica del Perú'),
('Viettel Perú'),
('América Móvil'),
('HUGHES DE PERÚ S.R.L.'),
('MINISTERIO DE TRANSPORTES Y COMUNICACIONES (MTC)'),
('CABLE PERÚ E.I.R.L'),
('ORGANISMO SUPERVISOR DE LA INVERSIÓN EN ENERGÍA Y MINERÍA (OSINERGMIN)'),
('CABLE JAEN S.R.L.'),
('SUPERINTENDENCIA NACIONAL DE SERVICIOS DE SANEAMIENTO (SUNASS)'),
('AT & T LATIN AMERICA'),
('CABLE VISION CHACHAPOYAS S.R.L.'),
('WINNER SYSTEMS S.A.C.'),
('CABLE FUTURO S.R.L.'),
('Entel Perú'),
('ECONOCABLE S.A.C.'),
('OLO DEL PERU S.A.C.'),
('HUASCARAN TELECOM S.A.C.'),
('ECONOCABLE PERÚ S.A.C.'),
('CABLEMAX E.I.R.L'),
('CABLE STAR PERÚ S.A.C.'),
('TV CABLE HUANTA'),
('GIGARED E.I.R.L.'),
('SUPERCABLE TELEVISION S.R.LTDA.'),
('CABLEMASS S.R.L.'),
('CABLEVISION S.A.C.'),
('GILAT TO HOME PERÚ S.A.'),
('FIBERLUX S.AC'),
('SERVICIO DE TELEFONIA Y COMUNICACIONES S.A. (SERTELCO S.A.)'),
('FENIX TELECOMMUNICATIONS HOLDING S.A.C'),
('CABLE MAS S.A.C.'),
('TELEMUNDO INTERNACIONAL E.I.R.L.'),
('GLOBAL COMMUNICATION S.R.L.'),
('INCACEL MOVIL S.A. (antes Virgin Mobile Perú S.A.)'),
('ANTENAS CABLE VISIÓN SATELITE S.A.C. - CABLE VISIÓN PERÚ'),
('CABLE CLUB S.C.R.LTDA'),
('CABLE VISION DEL CENTRO SRL'),
('IDT PERÚ S.R.L.'),
('TERRA NETWORKS PERU S.A.'),
('VIP CHANNEL SAC'),
('CABLE VISION'),
('EVELYN SAC.'),
('CONVERGIA PERÚ S.A.'),
('CABLE ESTACION S.R.L.'),
('WI-NET TELECOM S.A.C.'),
('CABLE AMERICA S.A.'),
('TV MAGICO E.I.R.L.'),
('CABLE YURIMAGUAS S.R.Ltda.'),
('CABLE VIDEO PERÚ S.A.C.'),
('TELEVISION SAN MARTIN S.A.C.'),
('WI-NET PERU S.A.C.'),
('AMITEL PERU TELECOMUNICACIONES S.A.C.'),
('CABLE MUNDO S.A.C.'),
('CABLE MEGAVISION E.I.R.L'),
('TELESERVICIOS E.I.R.L.'),
('RED INTERCABLE PERU S.A.C.'),
('CABLE BOX PERU E.I.R.L.'),
('TE.SA.M. PERU S.A.'),
('(en blanco)'),
('CABLE VISION ICA S.A.C'),
('TEL & WIFI'),
('NETWORKING SAT E.I.R.L'),
('SKY TELECOM PERU S.A.C'),
('FRAVATEL E.I.R.L.'),
('TELECABLE PERU S.A.C.'),
('TELECABLE SS S.A.C.'),
('J.R. TELECOM S.R.LTDA'),
('MI CABLE TV S.A.C.'),
('CATV SYSTEMS E.I.R.L.'),
('CABLE NETWORD S.R.L.'),
('CABLE VISION IQUITOS S.A.C.'),
('TELE CABLE IQUITOS S.A.C.'),
('CABLE VISION HUANUCO S.A.C.'),
('SITEL S.A.'),
('MEGA CABLE TV. SAC.'),
('MEGACABLE CLUB S.A.C.'),
('RED DE COMUNICACIONES DIGITALES S.A.C.'),
('GLOBAL BACKBONE S.A.C.'),
('DEVAOS ALTURA TELEVISION POR CABLE EMPRESA INDIVIDUAL DE RESPONSABIL'),
('OMNISAT COMUNICACIONES Y SERVICIOS S.R.L.'),
('COMUNICACIONES TRUJILLO S.A.C.'),
('ALEJANDRINA VIOLETA MEZA GAMARRA DE MINAYA'),
('GTD PERÚ S.A. ( antes WIGO S.A. y aún antes DIGITAL WAY S.A.)'),
('TESACOM PERU S.A.C.'),
('EMPRESA DIFUSORA CABLE MUNDO S.R.L.'),
('CABLE DIGITAL TV PERU S.A.C.'),
('FITEL'),
('CABLE NORTE S.A.C.'),
('CABLE ORIENTE S.A'),
('MICROSYSTEM NET COMUNICACIONES E.I.R.L.');


## SERVICIOS

INSERT INTO `servicios` (`nombre`) VALUES
('Telefonía Móvil'),
('OSIPTEL'),
('Televisión por cable'),
('Otros servicios'),
('Servicios Empaquetados'),
('Telefonía Fija'),
('Internet'),
('Telefonía Pública TPE/TPI'),
('Telefonía Pública TPI Ajena'),
('Tarjetas de Pago'),
('Arrendamiento de Circuitos');


## TEMA GENERAL

INSERT INTO `tema_general_orientacions` (`nombre`) VALUES
('Procedimiento de reclamo'),
('Usuario remite información adicional/ solicitada'),
('Atención de la empresa'),
('Cobro'),
('Contratación del servicio'),
('Suspensión / Corte'),
('Procedimiento en primera instancia (se reitera información)'),
('Baja de servicio'),
('OTROS (especificar)'),
('Facturación'),
('Recargas'),
('Calidad'),
('Equipos'),
('Portabilidad'),
('INDECOPI'),
('Empresas operadoras'),
('Información general'),
('Registro de llamadas entrantes'),
('Migración'),
('Instalación / Activación'),
('Tarifas'),
('CONSULTAS O SOLICITUDES'),
('Traslado'),
('Información / Veracidad'),
('Procedimiento para consultar número de líneas móviles'),
('Reposición SIM Card'),
('Devoluciones'),
('Activación'),
('Servicios en línea'),
('Recibos'),
('Información sobre servicio técnico/asistencia técnica de empresa'),
('Ministerio de Transportes y Comunicaciones'),
('Cambio de titularidad'),
('INDECOPIConsultas de competencia del INDECOPI'),
('OSINERGMIN'),
('Otros'),
('Cambio de numeración'),
('SUNASS'),
('Modalidades delictivas'),
('Titularidad'),
('Larga distancia'),
('Cuestionamiento de línea pre pago'),
('Identificación de llamadas entrantes'),
('Empresas que prestan servicios'),
('DEFENSORIA DEL PUEBLO'),
('Bloqueo / Desbloqueo'),
('Procedimiento de validación de datos con más de 10 líneas'),
('Charlas'),
('Empresa no entrega constancia de cuestionamiento de titularidad'),
('TRASU'),
('Registro prepago'),
('Facturación detallada'),
('No se ejecuta la Baja de servicio con titularidad cuestionada'),
('Guía páginas blancas'),
('Tecnología'),
('Area Virtual Móvil'),
('SBS'),
('OSITRAN'),
('VIA JUDICIAL/EXTRAJUDICIAL'),
('Verificación de incumplimiento con empresa operadora'),
('Tarjetas de Pago'),
('Empresa informa cambios tecnológicos en: sistemas, instalaciones, y/o equipos'),
('Prepago'),
('Empresa entrega formato distinto a cuestionamiento de titularidad'),
('Procedimiento de validación de datos de 6 a 10 líneas'),
('Llamadas cortadas'),
('Empresa no retira información de datos personales del registro de abonados web'),
('Contrato'),
('Actualización de titularidad del servicio móvil prepago (Artículo 1 numeral 1.5 del DS N° 003-2016-MTC)'),
('Telefonía Móvil'),
('Tarjetas prepago');